### ISSUE TITLE
No DHCPOFFERS received

### ISSUE THREAD

**Issue by kaitallaoua** [phillipdavidstearns/simcom_wwan-setup#1]
Very good tutorial, thank you for it. However I had the problem at the last step for setting up a 4G connection. When I ran `sudo dhclient -1 -v wwan0`, I would not get assigned an IP and got the error `No DHCPOFFERS received`. I am sharing my solution that I had to send `AT+CGDCONT=1,"IP","inet.bell.ca"` in minicom, where inet.bell.ca is the APN for Bell, my carrier. I had everything working on 3G with a mobile broadband connection through the Edit Connections tab in Ubuntu and realized that the only reason it was working was because it correctly guessed the APN for me automatically. 

So, by setting your APN where mine was "inet.bell.ca" by sending `AT+CGDCONT=1,"IP","inet.bell.ca"` in minicom, you should be able to solve a similar problem.

**Comment by nolandg** [comment]
I had 2 problems. 

The APN was not set correctly by default (thanks @kaitallaoua!). For anyone using Truphone global IOT sims, the APN is:
````bash
AT+CGDCONT=1,"IP","iot.truphone.com"
AT+CGDCONT=2,"IPV4V6","iot.truphone.com"
````

Second issue was the module was connected with the wrong protocol, defaulting to preferring a slightly stronger connection to a WCDMA provider. In WCDMA mode it couldn't do any LTE or get an IP address. So I had to force it to only connect with LTE:
`AT+CNMP=38`.
