### ISSUE TITLE
SMS Python Example

### ISSUE THREAD

**Issue by mzahana** [phillipdavidstearns/simcom_wwan-setup#2]
Thank you  @phillipdavidstearns fort the extremely useful instructions. It saved me long time.

I would like to ask if there is Python example on how to send SMS as the one provided by Waveshare is not working for me, the output is below.
```bahs
SIM7600X is starting:
SIM7600X is ready
Sending Short Message Test:
Setting SMS mode...
AT+CMGF=1 ERROR
AT+CMGF=1 back:	
Sending Short Message
AT+CMGS="<phone_number>" ERROR
AT+CMGS="<phone_number>" back:	
error0
Receive Short Message Test:

Please send message to phone <phone_number>
Setting SMS mode...
AT+CMGF=1 ERROR
AT+CMGF=1 back:	
AT+CPMS="SM","SM","SM" ERROR
AT+CPMS="SM","SM","SM" back:	
AT+CMGR=1 ERROR
AT+CMGR=1 back:	
error0
SIM7600X is loging off:
Good bye
```

**Comment by phillipdavidstearns** [comment]
I'm not sure I was ever able to reliably get this example working. When working manually with the module,  I setup up a terminal listening for and printing responses from its serial port and a second window to issue AT commands by piping the output to its serial port.

Something see [this part of the guide](https://github.com/phillipdavidstearns/simcom_wwan-setup#pure-bash-shell).
