### ISSUE TITLE
Obtaining GPS & Internet together

### ISSUE THREAD

**Issue by saiteja1904** [phillipdavidstearns/simcom_wwan-setup#4]
Hello Thanks for the detailed information but
I am not able to communicate to modem via THS when I connect USB
Is is possible to Get GPS via THS and establish 4G connection through USB? or any other methods also would really help
basically I want both GPS and 4G to run on startup
if so can you please share the details on how to setup Thanks

**Comment by phillipdavidstearns** [comment]
Sadly, I've not updated this repo in ages and I've not had a chance to tinker with GPS. I believe you should be able to find a way to enable GPS in the AT commands, but for this you'll have to dig into the manual for the specific commands. You should be able to issue commands via the serial port.
