### ISSUE TITLE
Spontaneous disconnecting from LTE Network

### ISSUE THREAD

**Issue by StefanBaar** [phillipdavidstearns/simcom_wwan-setup#5]
Hello, Thank you for the detailed explanation.

I installed the driver and have set everything according to the instruction. Following I setup the LTE and provider info through the ubuntu network manager gui. I can connect to the network, but I the connection drops randomly and does not reconnect.

Is there a way to connect to the network through the command line ... ?

**Comment by phillipdavidstearns** [comment]
I've not done work with this hardware for almost a year. Due to updates to the Jetson Nano platform, I'm unable to help with your issue. If you need to send AT commands to the module, you should be able to do so by piping stdio output to the appropriate serial port from the command line.

**Comment by palmerabollo** [comment]
@StefanBaar did you manage to reconnect the device every time it gets disconnected?
